### ISSUE TITLE
Remove need for the shell alias

### ISSUE THREAD

**Issue by LarsMichelsen** [nvbn/thefuck#4] opened 2015-04-17 19:31 UTC
In your doc you mention that one needs to create an alias in order to make thefuck work.

Is there a reason why you did not implement it the way that thefuck directly launches the new command without echoing it back to the subshell? This way it would be easier to setup.

**Comment by vikstrous** [comment] 2015-04-18 19:35
It seems like fish and bash both have the `history` command. The issue is that in fish the history is in reverse-chronological order, but in bash it's in chronological order. In bash it's prefixed with a number, in fish it's not. It requires detecting what shell you are using and testing with different shells. I don't think it's impossible. It's just harder.

**Comment by nvbn** [comment] 2015-04-18 19:42
Alias required because we can't get previous command from python script.

`$(... $(...))`  required for correct work of ncurses and strange-working-with-user-input apps.

**Comment by LaMi-** [comment] 2015-04-19 17:07
I did not find any other way to get the last command neither. The current bash has the last command only in memory which does not seem to be easily accessible from the python script.

It should be easier to replace the outer subshell, making the python script call the fixed command. Changing the way the commands are executed would make it also possible to let fuck decide whether or not execute commands directly, or showing them to the user for confirmation before executing them, for example by configuration.

However, when the alias is still needed it is irrelevant how complex it is. One could just make the installation easier. For example by deploying a config file below /etc/profile.d.

**Comment by scorphus** [comment] 2019-01-01 10:40
Closing this one for now.

**Closed by scorphus** 2019-01-01 10:40 UTC
