### ISSUE TITLE
Weird recommendations on arch + zsh

### ISSUE THREAD

**Issue by binarynoise** [nvbn/thefuck#1321] opened 2022-08-10 17:56 UTC
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    The Fuck 3.32 using Python 3.10.5 and ZSH 5.9

Your system (Debian 7, ArchLinux, Windows, etc.):

    ArchLinux (RebornOS)

How to reproduce the bug:

    > gti # or any other invalid command
    zsh: command not found: gti
    > f
    /usr/bin/nano /bin/sh +1 && gti [enter/↑/↓/ctrl+c]

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

```
> gti
zsh: command not found: gti
> f
DEBUG: Run with settings: {'alter_history': True,
 'debug': True,
 'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
 'exclude_rules': [],
 'excluded_search_path_prefixes': [],
 'history_limit': None,
 'instant_mode': False,
 'no_colors': False,
 'num_close_matches': 3,
 'priority': {},
 'repeat': False,
 'require_confirmation': True,
 'rules': [<const: All rules enabled>],
 'slow_commands': ['lein', 'react-native', 'gradle', './gradlew', 'vagrant'],
 'user_dir': PosixPath('/home/binarynoise/.config/thefuck'),
 'wait_command': 3,
 'wait_slow_command': 15}
DEBUG: Received output: /bin/sh: line 1: gti: command not found

DEBUG: Call: gti; with env: {'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'SESSION_MANAGER': 'local/precision-7510:@/tmp/.ICE-unix/1696,unix/precision-7510:/tmp/.ICE-unix/1696', 'GNOME_TERMINAL_SCREEN': '/org/gnome/Terminal/screen/c488d9a8_3f2f_452d_a425_eefc0ebca96e', 'LANG': 'C', 'XDG_CURRENT_DESKTOP': 'X-Cinnamon', 'PWD': '/home/binarynoise', 'GTK3_MODULES': 'xapp-gtk3-module', 'XDG_STATE_HOME': '/home/binarynoise/.local/state', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/binarynoise', 'XDG_DATA_HOME': '/home/binarynoise/.local/share', 'DESKTOP_SESSION': 'cinnamon', 'XDG_CONFIG_HOME': '/home/binarynoise/.config', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'USER': 'binarynoise', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'XDG_VTNR': '7', 'XDG_SEAT': 'seat0', 'BROWSER': '/usr/bin/firefox', 'GTK_MODULES': 'canberra-gtk-module', 'VTE_VERSION': '6800', 'XDG_SESSION_DESKTOP': 'cinnamon', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'GTK_OVERLAY_SCROLLING': '1', 'MAIL': '/var/spool/mail/binarynoise', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'LOGNAME': 'binarynoise', 'GNOME_TERMINAL_SERVICE': ':1.429', 'PATH': '/home/binarynoise/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:/home/binarynoise/.cache/zsh4humans/v5/fzf/bin', 'XDG_RUNTIME_DIR': '/run/user/1000', 'XDG_DATA_DIRS': '/home/binarynoise/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'XDG_SESSION_ID': '2', 'SHELL': '/usr/bin/zsh', 'XDG_SESSION_TYPE': 'x11', 'HOME': '/home/binarynoise', 'EDITOR': '/usr/bin/nano', 'MOTD_SHOWN': 'pam', 'QT_QPA_PLATFORMTHEME': 'qt5ct', 'LC_COLLATE': 'de_DE.UTF-8', 'CINNAMON_VERSION': '5.4.9', 'XAUTHORITY': '/home/binarynoise/.Xauthority', 'COLORTERM': 'truecolor', 'XDG_SESSION_CLASS': 'user', 'TERM': 'xterm-256color', 'GDMSESSION': 'cinnamon', 'DISPLAY': ':0', 'SHLVL': '1', 'OLDPWD': '/home/binarynoise', 'TERMINFO': '/home/binarynoise/.terminfo', 'MANPATH': '/home/binarynoise/.cache/zsh4humans/v5/fzf/man:', 'P9K_TTY': 'old', '_P9K_TTY': '/dev/pts/2', 'LESS': '-iRFXMx4', 'PAGER': 'less', 'LS_COLORS': 'fi=00:mi=00:mh=00:ln=01;36:or=01;31:di=01;34:ow=04;01;34:st=34:tw=04;34:pi=01;33:so=01;33:do=01;33:bd=01;33:cd=01;33:su=01;35:sg=01;35:ca=01;35:ex=01;32:no=38;5;248', 'LSCOLORS': 'ExGxDxDxCxDxDxFxFxexEx', 'TREE_COLORS': 'fi=00:mi=00:mh=00:ln=01;36:or=01;31:di=01;34:ow=01;34:st=34:tw=34:pi=01;33:so=01;33:do=01;33:bd=01;33:cd=01;33:su=01;35:sg=01;35:ca=01;35:ex=01;32', 'P9K_SSH': '0', 'GPG_TTY': '/dev/pts/2', 'GCC_COLORS': 'error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01', 'ANDROID_SDK_ROOT': '/home/binarynoise/bin/Android-Sdk', '_': '/usr/bin/thefuck', 'INFOPATH': '', 'XDG_CACHE_HOME': '/home/binarynoise/.cache', 'TF_SHELL': 'zsh', 'TF_ALIAS': 'f', 'TF_SHELL_ALIASES': "diff='diff --color=auto'\ngrep='grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}'\nipa='ip -4 -c -br a'\nla='ls -A'\nll='ls -alF'\nls='ls --color=auto -A'\ntree='tree -a -I .git'\nwhich-command=whence", 'PYTHONIOENCODING': 'utf-8', 'THEFUCK_DEBUG': 'true', 'TF_HISTORY': 'update-mime-database -v\nupdate-mime-database --help\nupdate-mime-database -h\nyay -S viper4linux-git viper4linux-gui gst-plugin-viper4linux-git libviperfx-nonfree-bin\nyay -S viper4linux-gui\nyay -S viper4linux-git\nyay -S thefuck\nexec zsh\nthefuck --version\ngti', 'LC_ALL': 'C', 'GIT_TRACE': '1'}; is slow: False took: 0:00:00.002641
DEBUG: Importing rule: adb_unknown_command; took: 0:00:00.000231
DEBUG: Importing rule: ag_literal; took: 0:00:00.000243
DEBUG: Importing rule: apt_get; took: 0:00:00.000735
DEBUG: Importing rule: apt_get_search; took: 0:00:00.000213
DEBUG: Importing rule: apt_invalid_operation; took: 0:00:00.000478
DEBUG: Importing rule: apt_list_upgradable; took: 0:00:00.000243
DEBUG: Importing rule: apt_upgrade; took: 0:00:00.000407
DEBUG: Importing rule: aws_cli; took: 0:00:00.000211
DEBUG: Importing rule: az_cli; took: 0:00:00.000244
DEBUG: Importing rule: brew_cask_dependency; took: 0:00:00.000515
DEBUG: Importing rule: brew_install; took: 0:00:00.000154
DEBUG: Importing rule: brew_link; took: 0:00:00.000199
DEBUG: Importing rule: brew_reinstall; took: 0:00:00.000527
DEBUG: Importing rule: brew_uninstall; took: 0:00:00.000216
DEBUG: Importing rule: brew_unknown_command; took: 0:00:00.000167
DEBUG: Importing rule: brew_update_formula; took: 0:00:00.000210
DEBUG: Importing rule: cargo; took: 0:00:00.000131
DEBUG: Importing rule: cargo_no_command; took: 0:00:00.000197
DEBUG: Importing rule: cat_dir; took: 0:00:00.000209
DEBUG: Importing rule: cd_correction; took: 0:00:00.000833
DEBUG: Importing rule: cd_cs; took: 0:00:00.000148
DEBUG: Importing rule: cd_mkdir; took: 0:00:00.000311
DEBUG: Importing rule: cd_parent; took: 0:00:00.000139
DEBUG: Importing rule: chmod_x; took: 0:00:00.000135
DEBUG: Importing rule: choco_install; took: 0:00:00.000444
DEBUG: Importing rule: composer_not_command; took: 0:00:00.000223
DEBUG: Importing rule: conda_mistype; took: 0:00:00.000229
DEBUG: Importing rule: cp_create_destination; took: 0:00:00.000237
DEBUG: Importing rule: cp_omitting_directory; took: 0:00:00.000256
DEBUG: Importing rule: cpp11; took: 0:00:00.000198
DEBUG: Importing rule: dirty_untar; took: 0:00:00.001740
DEBUG: Importing rule: dirty_unzip; took: 0:00:00.000263
DEBUG: Importing rule: django_south_ghost; took: 0:00:00.000150
DEBUG: Importing rule: django_south_merge; took: 0:00:00.000144
DEBUG: Importing rule: dnf_no_such_command; took: 0:00:00.000702
DEBUG: Importing rule: docker_image_being_used_by_container; took: 0:00:00.000238
DEBUG: Importing rule: docker_login; took: 0:00:00.000209
DEBUG: Importing rule: docker_not_command; took: 0:00:00.000532
DEBUG: Importing rule: dry; took: 0:00:00.000194
DEBUG: Importing rule: fab_command_not_found; took: 0:00:00.000328
DEBUG: Importing rule: fix_alt_space; took: 0:00:00.000279
DEBUG: Importing rule: fix_file; took: 0:00:00.003550
DEBUG: Importing rule: gem_unknown_command; took: 0:00:00.000536
DEBUG: Importing rule: git_add; took: 0:00:00.000622
DEBUG: Importing rule: git_add_force; took: 0:00:00.000319
DEBUG: Importing rule: git_bisect_usage; took: 0:00:00.000278
DEBUG: Importing rule: git_branch_0flag; took: 0:00:00.000322
DEBUG: Importing rule: git_branch_delete; took: 0:00:00.000280
DEBUG: Importing rule: git_branch_delete_checked_out; took: 0:00:00.000294
DEBUG: Importing rule: git_branch_exists; took: 0:00:00.000305
DEBUG: Importing rule: git_branch_list; took: 0:00:00.000311
DEBUG: Importing rule: git_checkout; took: 0:00:00.000328
DEBUG: Importing rule: git_clone_git_clone; took: 0:00:00.000293
DEBUG: Importing rule: git_commit_add; took: 0:00:00.000427
DEBUG: Importing rule: git_commit_amend; took: 0:00:00.000236
DEBUG: Importing rule: git_commit_reset; took: 0:00:00.000238
DEBUG: Importing rule: git_diff_no_index; took: 0:00:00.000383
DEBUG: Importing rule: git_diff_staged; took: 0:00:00.000881
DEBUG: Importing rule: git_fix_stash; took: 0:00:00.000592
DEBUG: Importing rule: git_flag_after_filename; took: 0:00:00.000252
DEBUG: Importing rule: git_help_aliased; took: 0:00:00.000220
DEBUG: Importing rule: git_hook_bypass; took: 0:00:00.000220
DEBUG: Importing rule: git_lfs_mistype; took: 0:00:00.000217
DEBUG: Importing rule: git_main_master; took: 0:00:00.000209
DEBUG: Importing rule: git_merge; took: 0:00:00.000307
DEBUG: Importing rule: git_merge_unrelated; took: 0:00:00.001020
DEBUG: Importing rule: git_not_command; took: 0:00:00.000744
DEBUG: Importing rule: git_pull; took: 0:00:00.000415
DEBUG: Importing rule: git_pull_clone; took: 0:00:00.000375
DEBUG: Importing rule: git_pull_uncommitted_changes; took: 0:00:00.000513
DEBUG: Importing rule: git_push; took: 0:00:00.000314
DEBUG: Importing rule: git_push_different_branch_names; took: 0:00:00.000361
DEBUG: Importing rule: git_push_force; took: 0:00:00.000265
DEBUG: Importing rule: git_push_pull; took: 0:00:00.000376
DEBUG: Importing rule: git_push_without_commits; took: 0:00:00.000281
DEBUG: Importing rule: git_rebase_merge_dir; took: 0:00:00.000328
DEBUG: Importing rule: git_rebase_no_changes; took: 0:00:00.000262
DEBUG: Importing rule: git_remote_delete; took: 0:00:00.000267
DEBUG: Importing rule: git_remote_seturl_add; took: 0:00:00.000242
DEBUG: Importing rule: git_rm_local_modifications; took: 0:00:00.000306
DEBUG: Importing rule: git_rm_recursive; took: 0:00:00.000323
DEBUG: Importing rule: git_rm_staged; took: 0:00:00.000296
DEBUG: Importing rule: git_stash; took: 0:00:00.000262
DEBUG: Importing rule: git_stash_pop; took: 0:00:00.000277
DEBUG: Importing rule: git_tag_force; took: 0:00:00.000293
DEBUG: Importing rule: git_two_dashes; took: 0:00:00.000289
DEBUG: Importing rule: go_run; took: 0:00:00.000379
DEBUG: Importing rule: go_unknown_command; took: 0:00:00.000518
DEBUG: Importing rule: gradle_no_task; took: 0:00:00.000675
DEBUG: Importing rule: gradle_wrapper; took: 0:00:00.000287
DEBUG: Importing rule: grep_arguments_order; took: 0:00:00.000278
DEBUG: Importing rule: grep_recursive; took: 0:00:00.000263
DEBUG: Importing rule: grunt_task_not_found; took: 0:00:00.000573
DEBUG: Importing rule: gulp_not_task; took: 0:00:00.000297
DEBUG: Importing rule: has_exists_script; took: 0:00:00.000267
DEBUG: Importing rule: heroku_multiple_apps; took: 0:00:00.000266
DEBUG: Importing rule: heroku_not_command; took: 0:00:00.000297
DEBUG: Importing rule: history; took: 0:00:00.000186
DEBUG: Importing rule: hostscli; took: 0:00:00.000326
DEBUG: Importing rule: ifconfig_device_not_found; took: 0:00:00.000298
DEBUG: Importing rule: java; took: 0:00:00.000257
DEBUG: Importing rule: javac; took: 0:00:00.000356
DEBUG: Importing rule: lein_not_task; took: 0:00:00.000327
DEBUG: Importing rule: ln_no_hard_link; took: 0:00:00.000265
DEBUG: Importing rule: ln_s_order; took: 0:00:00.000256
DEBUG: Importing rule: long_form_help; took: 0:00:00.000177
DEBUG: Importing rule: ls_all; took: 0:00:00.000259
DEBUG: Importing rule: ls_lah; took: 0:00:00.000226
DEBUG: Importing rule: man; took: 0:00:00.000241
DEBUG: Importing rule: man_no_space; took: 0:00:00.000168
DEBUG: Importing rule: mercurial; took: 0:00:00.000292
DEBUG: Importing rule: missing_space_before_subcommand; took: 0:00:00.000205
DEBUG: Importing rule: mkdir_p; took: 0:00:00.000284
DEBUG: Importing rule: mvn_no_command; took: 0:00:00.000295
DEBUG: Importing rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000299
DEBUG: Importing rule: nixos_cmd_not_found; took: 0:00:00.000791
DEBUG: Importing rule: no_command; took: 0:00:00.000328
DEBUG: Importing rule: no_such_file; took: 0:00:00.000153
DEBUG: Importing rule: npm_missing_script; took: 0:00:00.000524
DEBUG: Importing rule: npm_run_script; took: 0:00:00.001237
DEBUG: Importing rule: npm_wrong_command; took: 0:00:00.000369
DEBUG: Importing rule: omnienv_no_such_command; took: 0:00:00.000560
DEBUG: Importing rule: open; took: 0:00:00.000250
DEBUG: Importing rule: pacman; took: 0:00:00.000444
DEBUG: Importing rule: pacman_invalid_option; took: 0:00:00.000286
DEBUG: Importing rule: pacman_not_found; took: 0:00:00.000223
DEBUG: Importing rule: path_from_history; took: 0:00:00.000251
DEBUG: Importing rule: php_s; took: 0:00:00.000289
DEBUG: Importing rule: pip_install; took: 0:00:00.000481
DEBUG: Importing rule: pip_unknown_command; took: 0:00:00.001149
DEBUG: Importing rule: port_already_in_use; took: 0:00:00.000588
DEBUG: Importing rule: prove_recursively; took: 0:00:00.000384
DEBUG: Importing rule: python_command; took: 0:00:00.000284
DEBUG: Importing rule: python_execute; took: 0:00:00.000274
DEBUG: Importing rule: python_module_error; took: 0:00:00.000354
DEBUG: Importing rule: quotation_marks; took: 0:00:00.000698
DEBUG: Importing rule: rails_migrations_pending; took: 0:00:00.000272
DEBUG: Importing rule: react_native_command_unrecognized; took: 0:00:00.014503
DEBUG: Importing rule: remove_shell_prompt_literal; took: 0:00:00.000232
DEBUG: Importing rule: remove_trailing_cedilla; took: 0:00:00.000158
DEBUG: Importing rule: rm_dir; took: 0:00:00.000220
DEBUG: Importing rule: rm_root; took: 0:00:00.000212
DEBUG: Importing rule: scm_correction; took: 0:00:00.000251
DEBUG: Importing rule: sed_unterminated_s; took: 0:00:00.000236
DEBUG: Importing rule: sl_ls; took: 0:00:00.000147
DEBUG: Importing rule: ssh_known_hosts; took: 0:00:00.000232
DEBUG: Importing rule: sudo; took: 0:00:00.000158
DEBUG: Importing rule: sudo_command_from_user_path; took: 0:00:00.000229
DEBUG: Importing rule: switch_lang; took: 0:00:00.000256
DEBUG: Importing rule: systemctl; took: 0:00:00.000259
DEBUG: Importing rule: terraform_init; took: 0:00:00.000218
DEBUG: Importing rule: test.py; took: 0:00:00.000192
DEBUG: Importing rule: tmux; took: 0:00:00.000234
DEBUG: Importing rule: touch; took: 0:00:00.000214
DEBUG: Importing rule: tsuru_login; took: 0:00:00.000295
DEBUG: Importing rule: tsuru_not_command; took: 0:00:00.000299
DEBUG: Importing rule: unknown_command; took: 0:00:00.000192
DEBUG: Importing rule: unsudo; took: 0:00:00.000189
DEBUG: Importing rule: vagrant_up; took: 0:00:00.000287
DEBUG: Importing rule: whois; took: 0:00:00.000386
DEBUG: Importing rule: workon_doesnt_exists; took: 0:00:00.000333
DEBUG: Importing rule: wrong_hyphen_before_subcommand; took: 0:00:00.000266
DEBUG: Importing rule: yarn_alias; took: 0:00:00.000224
DEBUG: Importing rule: yarn_command_not_found; took: 0:00:00.000529
DEBUG: Importing rule: yarn_command_replaced; took: 0:00:00.000454
DEBUG: Importing rule: yarn_help; took: 0:00:00.000232
DEBUG: Importing rule: yum_invalid_operation; took: 0:00:00.000556
DEBUG: Trying rule: path_from_history; took: 0:00:00.000524
DEBUG: Trying rule: cd_cs; took: 0:00:00.000038
DEBUG: Trying rule: dry; took: 0:00:00.000003
DEBUG: Trying rule: git_stash_pop; took: 0:00:00.000050
DEBUG: Trying rule: test.py; took: 0:00:00.000002
DEBUG: Trying rule: adb_unknown_command; took: 0:00:00.000014
DEBUG: Trying rule: ag_literal; took: 0:00:00.000027
DEBUG: Trying rule: aws_cli; took: 0:00:00.000023
DEBUG: Trying rule: az_cli; took: 0:00:00.000022
DEBUG: Trying rule: brew_link; took: 0:00:00.000029
DEBUG: Trying rule: brew_reinstall; took: 0:00:00.000019
DEBUG: Trying rule: brew_uninstall; took: 0:00:00.000017
DEBUG: Trying rule: brew_update_formula; took: 0:00:00.000018
DEBUG: Trying rule: cargo; took: 0:00:00.000002
DEBUG: Trying rule: cargo_no_command; took: 0:00:00.000019
DEBUG: Trying rule: cat_dir; took: 0:00:00.000019
DEBUG: Trying rule: cd_correction; took: 0:00:00.000029
DEBUG: Trying rule: cd_mkdir; took: 0:00:00.000025
DEBUG: Trying rule: cd_parent; took: 0:00:00.000001
DEBUG: Trying rule: chmod_x; took: 0:00:00.000001
DEBUG: Trying rule: composer_not_command; took: 0:00:00.000020
DEBUG: Trying rule: conda_mistype; took: 0:00:00.000020
DEBUG: Trying rule: cp_create_destination; took: 0:00:00.000020
DEBUG: Trying rule: cp_omitting_directory; took: 0:00:00.000027
DEBUG: Trying rule: cpp11; took: 0:00:00.000019
DEBUG: Trying rule: dirty_untar; took: 0:00:00.000019
DEBUG: Trying rule: dirty_unzip; took: 0:00:00.000020
DEBUG: Trying rule: django_south_ghost; took: 0:00:00.000002
DEBUG: Trying rule: django_south_merge; took: 0:00:00.000001
DEBUG: Trying rule: docker_image_being_used_by_container; took: 0:00:00.000020
DEBUG: Trying rule: docker_login; took: 0:00:00.000016
DEBUG: Trying rule: docker_not_command; took: 0:00:00.000024
DEBUG: Trying rule: fab_command_not_found; took: 0:00:00.000024
DEBUG: Trying rule: fix_alt_space; took: 0:00:00.000012
DEBUG: Trying rule: fix_file; took: 0:00:00.000033
/usr/bin/nano /bin/sh +1 && gti [enter/↑/↓/ctrl+c]
```

If the bug only appears with a specific application, the output of that application and its version:

    FILL THIS IN

Anything else you think is relevant:

installed via z4h plugin:
.zshrc
```
# thefuck
command -v thefuck &>/dev/null
if [ $? -ne 0 ]; then
    echo "thefuck is missing" >&2
fi
z4h install laggardkernel/zsh-thefuck || return

zstyle ":prezto:module:thefuck" bindkey "no"
zstyle ":prezto:module:thefuck" alias "f"
z4h source $Z4H/laggardkernel/zsh-thefuck/zsh-thefuck.plugin.zsh
```

**Comment by CleanMachine1** [comment] 2022-08-29 17:25
Also getting the same thing of it trying to edit /bin/sh in the default editor.

**Comment by scorphus** [comment] 2022-08-31 18:36
Duplicate of #1153.

Check https://github.com/nvbn/thefuck/issues/1153#issuecomment-900415620 for a solution.

**Closed by scorphus** 2022-08-31 18:36 UTC
