### ISSUE TITLE
Needs a sudo pip install pathlib on Raspberry PI

### ISSUE THREAD

**Issue by mlk** [nvbn/thefuck#336] opened 2015-08-14 15:53 UTC
Might be worth adding in the readme somewhere.

**Comment by mcarton** [comment] 2015-08-14 22:18
This is [already taken care of](https://github.com/nvbn/thefuck/blob/d20205249b1b66ea1fa192069e3569fe54e3a0a7/setup.py#L26).
How did you install The Fuck?

**Comment by mlk** [comment] 2015-08-15 06:26
```
$ sudo apt-get install python-pip python-dev
$ sudo pip install psutil thefuck
Requirement already satisfied (use --upgrade to upgrade): psutil in /usr/local/lib/python2.7/dist-packages
Downloading/unpacking thefuck
  Downloading thefuck-2.7.tar.gz (47Kb): 47Kb downloaded
  Running setup.py egg_info for package thefuck

Requirement already satisfied (use --upgrade to upgrade): colorama in /usr/local/lib/python2.7/dist-packages (from thefuck)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from thefuck)
Installing collected packages: thefuck
  Running setup.py install for thefuck

    Installing thefuck-alias script to /usr/local/bin
    Installing thefuck script to /usr/local/bin
Successfully installed thefuck

$ fuck
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==2.7', 'console_scripts', 'thefuck')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/thefuck/main.py", line 3, in <module>
    from pathlib import Path
ImportError: No module named pathlib

$ sudo pip install pathlib
Downloading/unpacking pathlib
  Downloading pathlib-1.0.1.tar.gz (49Kb): 49Kb downloaded
  Running setup.py egg_info for package pathlib

Installing collected packages: pathlib
  Running setup.py install for pathlib

Successfully installed pathlib
Cleaning up...

$ apt-get install thefuckworksnow
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?

$ fuck
sudo apt-get install thefuckworksnow [enter/↑/↓/ctrl+c]
```

OS Version:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.8 (wheezy)
Release:        7.8
Codename:       wheezy
```

Python version:
```
 $ python --version
Python 2.7.3
```

PIP version
```
$ pip --version
pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```

Anything else you need please let me know,

**Comment by SanketDG** [comment] 2015-08-15 06:47
@mlk You might want to upgrade `pip` though. Your version is ancient, although I am not sure that doing that would fix this.

**Comment by mcarton** [comment] 2015-08-15 10:51
It seems `pip` ignored that [*extras_require*](https://github.com/pypa/pip/issues/7) kind of marker until [version 6.0](https://github.com/pypa/pip/pull/2153).

**Comment by nvbn** [comment] 2015-08-16 18:13
@mcarton I guess I should add something like install script that used in docker-compose (https://github.com/docker/compose) for fixing dependencies problems.

**Comment by sylvainar** [comment] 2015-08-26 13:03
Hey guys !

I've successfully installed The Fuck on my Raspberry Pi, it's awesome !

The only problem is that it's really, really slow (I've got a result 2 or 3 seconds after I typed "fuck"). Do you know why ?

Thanks !

**Comment by mcarton** [comment] 2015-08-26 14:07
The slowness has already [been reported](https://github.com/nvbn/thefuck/issues/334).
The problem is that there are now a lot of rules, each taking a small amount of time. Unfortunately maths are against us there.
Try deactivating some rules you don't use (eg. the `history`, which is the slowest as far as I know).
I also noticed that getting the aliases list from the shell is quiet slow. On my system this takes up to 400ms, about half the time needed to execute `fuck`:
```
% time zsh -ic alias
…            
zsh -ic exit  0.35s user 0.04s system 96% cpu 0.410 total
```
I should clean up my `.zshrc`.
And of course, a raspberry pi is not the fastest computer there is.

**Comment by SanketDG** [comment] 2015-08-26 14:07
#345 fixes a lot of slowness problems. Make sure you have version 2.8.

**Comment by mcarton** [comment] 2015-08-26 14:10
@SanketDG Well, #345 really fixes *one* problem, but it was the more important overhead for me. And the fix is indeed included in 2.8.

**Comment by radzio1993** [comment] 2016-07-30 16:54
```
sudo apt-get install python-pip python-dev
sudo pip install psutil thefuck
```
...
...
----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-LOfHb8/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mc85LC-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-LOfHb8/psutil
Storing debug log for failure in /root/.pip/pip.log

**Comment by nvbn** [comment] 2017-03-14 08:41
We're checking `pip` version in `setup.py` already for a while, so this issue is obsolete.

**Closed by nvbn** 2017-03-14 08:41 UTC
Labels: obsolete
