### ISSUE TITLE
Quoted arguments not preserved as a single token in no_command rule

### ISSUE THREAD

**Issue by rpdelaney** [nvbn/thefuck#1084] opened 2020-05-01 23:57 UTC
> The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

```
$ thefuck --version
The Fuck 3.30 using Python 3.8.2 and Bash 5.0.16(1)-release
```

> Your system (Debian 7, ArchLinux, Windows, etc.):

`macOS-10.15.4`

> How to reproduce the bug:

`gi c -m "a commit message here"`

> The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

I have redacted parts of this because I am not comfortable sharing my environment variables in a public github issue.

<details><summary>Debug output</summary>

```
$ gi commit -m "a commit message here"
DEBUG: Run with settings: {'alter_history': True,
 'debug': True,
 'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},
 'exclude_rules': [],
 'history_limit': None,
 'instant_mode': False,
 'no_colors': False,
 'num_close_matches': 3,
 'priority': {},
 'repeat': False,
 'require_confirmation': True,
 'rules': [<const: All rules enabled>],
 'slow_commands': ['lein', 'react-native', 'gradle', './gradlew', 'vagrant'],
 'user_dir': PosixPath('/Users/ryan/Preferences/thefuck'),
 'wait_command': 3,
 'wait_slow_command': 15}
DEBUG: Received output: /bin/sh: gi: command not found

DEBUG: Call: gi c -m "a commit message here"; with env: REDACTED; is slow: False took: 0:00:00.004493

DEBUG: Importing rule: adb_unknown_command; took: 0:00:00.000261
DEBUG: Importing rule: ag_literal; took: 0:00:00.000470
DEBUG: Importing rule: apt_get; took: 0:00:00.001015
DEBUG: Importing rule: apt_get_search; took: 0:00:00.000285
DEBUG: Importing rule: apt_invalid_operation; took: 0:00:00.000814
DEBUG: Importing rule: apt_list_upgradable; took: 0:00:00.000453
DEBUG: Importing rule: apt_upgrade; took: 0:00:00.000452
DEBUG: Importing rule: aws_cli; took: 0:00:00.000417
DEBUG: Importing rule: az_cli; took: 0:00:00.000330
DEBUG: Importing rule: brew_cask_dependency; took: 0:00:00.000626
DEBUG: Importing rule: brew_install; took: 0:00:00.000174
DEBUG: Importing rule: brew_link; took: 0:00:00.000281
DEBUG: Importing rule: brew_reinstall; took: 0:00:00.000602
DEBUG: Importing rule: brew_uninstall; took: 0:00:00.000297
DEBUG: Importing rule: brew_unknown_command; took: 0:00:00.000200
DEBUG: Importing rule: brew_update_formula; took: 0:00:00.000343
DEBUG: Importing rule: cargo; took: 0:00:00.000125
DEBUG: Importing rule: cargo_no_command; took: 0:00:00.000332
DEBUG: Importing rule: cat_dir; took: 0:00:00.000288
DEBUG: Importing rule: cd_correction; took: 0:00:00.001244
DEBUG: Importing rule: cd_mkdir; took: 0:00:00.000409
DEBUG: Importing rule: cd_parent; took: 0:00:00.000146
DEBUG: Importing rule: chmod_x; took: 0:00:00.000128
DEBUG: Importing rule: choco_install; took: 0:00:00.000679
DEBUG: Importing rule: composer_not_command; took: 0:00:00.000360
DEBUG: Importing rule: cp_create_destination; took: 0:00:00.000288
DEBUG: Importing rule: cp_omitting_directory; took: 0:00:00.000412
DEBUG: Importing rule: cpp11; took: 0:00:00.000297
DEBUG: Importing rule: dirty_untar; took: 0:00:00.001138
DEBUG: Importing rule: dirty_unzip; took: 0:00:00.001436
DEBUG: Importing rule: django_south_ghost; took: 0:00:00.000136
DEBUG: Importing rule: django_south_merge; took: 0:00:00.000127
DEBUG: Importing rule: dnf_no_such_command; took: 0:00:00.001182
DEBUG: Importing rule: docker_image_being_used_by_container; took: 0:00:00.000352
DEBUG: Importing rule: docker_login; took: 0:00:00.000327
DEBUG: Importing rule: docker_not_command; took: 0:00:00.000556
DEBUG: Importing rule: dry; took: 0:00:00.000135
DEBUG: Importing rule: fab_command_not_found; took: 0:00:00.000375
DEBUG: Importing rule: fix_alt_space; took: 0:00:00.000287
DEBUG: Importing rule: fix_file; took: 0:00:00.001804
DEBUG: Importing rule: gem_unknown_command; took: 0:00:00.000482
DEBUG: Importing rule: git_add; took: 0:00:00.000534
DEBUG: Importing rule: git_add_force; took: 0:00:00.000318
DEBUG: Importing rule: git_bisect_usage; took: 0:00:00.000319
DEBUG: Importing rule: git_branch_delete; took: 0:00:00.000357
DEBUG: Importing rule: git_branch_delete_checked_out; took: 0:00:00.000279
DEBUG: Importing rule: git_branch_exists; took: 0:00:00.000348
DEBUG: Importing rule: git_branch_list; took: 0:00:00.000275
DEBUG: Importing rule: git_checkout; took: 0:00:00.000345
DEBUG: Importing rule: git_commit_amend; took: 0:00:00.000312
DEBUG: Importing rule: git_commit_reset; took: 0:00:00.000308
DEBUG: Importing rule: git_diff_no_index; took: 0:00:00.000347
DEBUG: Importing rule: git_diff_staged; took: 0:00:00.000311
DEBUG: Importing rule: git_fix_stash; took: 0:00:00.000360
DEBUG: Importing rule: git_flag_after_filename; took: 0:00:00.000317
DEBUG: Importing rule: git_help_aliased; took: 0:00:00.000275
DEBUG: Importing rule: git_merge; took: 0:00:00.000312
DEBUG: Importing rule: git_merge_unrelated; took: 0:00:00.000341
DEBUG: Importing rule: git_not_command; took: 0:00:00.000348
DEBUG: Importing rule: git_pull; took: 0:00:00.000311
DEBUG: Importing rule: git_pull_clone; took: 0:00:00.000348
DEBUG: Importing rule: git_pull_uncommitted_changes; took: 0:00:00.000349
DEBUG: Importing rule: git_push; took: 0:00:00.000313
DEBUG: Importing rule: git_push_different_branch_names; took: 0:00:00.000371
DEBUG: Importing rule: git_push_force; took: 0:00:00.000286
DEBUG: Importing rule: git_push_pull; took: 0:00:00.000285
DEBUG: Importing rule: git_push_without_commits; took: 0:00:00.000319
DEBUG: Importing rule: git_rebase_merge_dir; took: 0:00:00.000317
DEBUG: Importing rule: git_rebase_no_changes; took: 0:00:00.000208
DEBUG: Importing rule: git_remote_delete; took: 0:00:00.000341
DEBUG: Importing rule: git_remote_seturl_add; took: 0:00:00.000209
DEBUG: Importing rule: git_rm_local_modifications; took: 0:00:00.000308
DEBUG: Importing rule: git_rm_recursive; took: 0:00:00.000351
DEBUG: Importing rule: git_rm_staged; took: 0:00:00.000318                                                                                                         [198/10000]
DEBUG: Importing rule: git_stash; took: 0:00:00.000310
DEBUG: Importing rule: git_stash_pop; took: 0:00:00.000301
DEBUG: Importing rule: git_tag_force; took: 0:00:00.000303
DEBUG: Importing rule: git_two_dashes; took: 0:00:00.000308
DEBUG: Importing rule: go_run; took: 0:00:00.000314
DEBUG: Importing rule: go_unknown_command; took: 0:00:00.000414
DEBUG: Importing rule: gradle_no_task; took: 0:00:00.000519
DEBUG: Importing rule: gradle_wrapper; took: 0:00:00.000288
DEBUG: Importing rule: grep_arguments_order; took: 0:00:00.000317
DEBUG: Importing rule: grep_recursive; took: 0:00:00.000317
DEBUG: Importing rule: grunt_task_not_found; took: 0:00:00.000498
DEBUG: Importing rule: gulp_not_task; took: 0:00:00.000326
DEBUG: Importing rule: has_exists_script; took: 0:00:00.000280
DEBUG: Importing rule: heroku_multiple_apps; took: 0:00:00.000285
DEBUG: Importing rule: heroku_not_command; took: 0:00:00.000285
DEBUG: Importing rule: history; took: 0:00:00.000134
DEBUG: Importing rule: hostscli; took: 0:00:00.000455
DEBUG: Importing rule: ifconfig_device_not_found; took: 0:00:00.000348
DEBUG: Importing rule: java; took: 0:00:00.000284
DEBUG: Importing rule: javac; took: 0:00:00.000280
DEBUG: Importing rule: lein_not_task; took: 0:00:00.000414
DEBUG: Importing rule: ln_no_hard_link; took: 0:00:00.000322
DEBUG: Importing rule: ln_s_order; took: 0:00:00.000599
DEBUG: Importing rule: long_form_help; took: 0:00:00.000336
DEBUG: Importing rule: ls_all; took: 0:00:00.000533
DEBUG: Importing rule: ls_lah; took: 0:00:00.000358
DEBUG: Importing rule: man; took: 0:00:00.000401
DEBUG: Importing rule: man_no_space; took: 0:00:00.000228
DEBUG: Importing rule: mercurial; took: 0:00:00.000464
DEBUG: Importing rule: missing_space_before_subcommand; took: 0:00:00.000175
DEBUG: Importing rule: mkdir_p; took: 0:00:00.000309
DEBUG: Importing rule: mvn_no_command; took: 0:00:00.000319
DEBUG: Importing rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000320
DEBUG: Importing rule: nixos_cmd_not_found; took: 0:00:00.000751
DEBUG: Importing rule: no_command; took: 0:00:00.000308
DEBUG: Importing rule: no_such_file; took: 0:00:00.000178
DEBUG: Importing rule: npm_missing_script; took: 0:00:00.000952
DEBUG: Importing rule: npm_wrong_command; took: 0:00:00.000542                                                                                                     [159/10000]
DEBUG: Importing rule: open; took: 0:00:00.000369
DEBUG: Importing rule: pacman; took: 0:00:00.000735
DEBUG: Importing rule: pacman_not_found; took: 0:00:00.000145
DEBUG: Importing rule: path_from_history; took: 0:00:00.000153
DEBUG: Importing rule: php_s; took: 0:00:00.000299
DEBUG: Importing rule: pip_install; took: 0:00:00.000361
DEBUG: Importing rule: pip_unknown_command; took: 0:00:00.000360
DEBUG: Importing rule: port_already_in_use; took: 0:00:00.000352
DEBUG: Importing rule: prove_recursively; took: 0:00:00.000335
DEBUG: Importing rule: pyenv_no_such_command; took: 0:00:00.000562
DEBUG: Importing rule: python_command; took: 0:00:00.000282
DEBUG: Importing rule: python_execute; took: 0:00:00.000289
DEBUG: Importing rule: quotation_marks; took: 0:00:00.000135
DEBUG: Importing rule: react_native_command_unrecognized; took: 0:00:00.000367
DEBUG: Importing rule: remove_shell_prompt_literal; took: 0:00:00.000137
DEBUG: Importing rule: remove_trailing_cedilla; took: 0:00:00.000128
DEBUG: Importing rule: rm_dir; took: 0:00:00.000341
DEBUG: Importing rule: rm_root; took: 0:00:00.000288
DEBUG: Importing rule: scm_correction; took: 0:00:00.000306
DEBUG: Importing rule: sed_unterminated_s; took: 0:00:00.000334
DEBUG: Importing rule: sl_ls; took: 0:00:00.000133
DEBUG: Importing rule: ssh_known_hosts; took: 0:00:00.000287
DEBUG: Importing rule: sudo; took: 0:00:00.000138
DEBUG: Importing rule: sudo_command_from_user_path; took: 0:00:00.000302
DEBUG: Importing rule: switch_lang; took: 0:00:00.000196
DEBUG: Importing rule: systemctl; took: 0:00:00.000430
DEBUG: Importing rule: terraform_init; took: 0:00:00.000291
DEBUG: Importing rule: test.py; took: 0:00:00.000136
DEBUG: Importing rule: tmux; took: 0:00:00.000287
DEBUG: Importing rule: touch; took: 0:00:00.000301
DEBUG: Importing rule: tsuru_login; took: 0:00:00.000292
DEBUG: Importing rule: tsuru_not_command; took: 0:00:00.000293
DEBUG: Importing rule: unknown_command; took: 0:00:00.000135
DEBUG: Importing rule: unsudo; took: 0:00:00.000127
DEBUG: Importing rule: vagrant_up; took: 0:00:00.000287
DEBUG: Importing rule: whois; took: 0:00:00.000446
DEBUG: Importing rule: workon_doesnt_exists; took: 0:00:00.000777
DEBUG: Importing rule: yarn_alias; took: 0:00:00.000332                                                                                                            [121/10000]
DEBUG: Importing rule: yarn_command_not_found; took: 0:00:00.000598
DEBUG: Importing rule: yarn_command_replaced; took: 0:00:00.000436
DEBUG: Importing rule: yarn_help; took: 0:00:00.000323
DEBUG: Importing rule: yum_invalid_operation; took: 0:00:00.000774
DEBUG: Importing rule: docker_containers; took: 0:00:00.000290
DEBUG: Importing rule: mpv_yt; took: 0:00:00.000470
DEBUG: Importing rule: terraform_init.bak; took: 0:00:00.000170
DEBUG: Importing rule: terraform_init; took: 0:00:00.000344
DEBUG: Trying rule: path_from_history; took: 0:00:00.000409
DEBUG: Trying rule: dry; took: 0:00:00.000065
DEBUG: Trying rule: git_stash_pop; took: 0:00:00.000016
DEBUG: Trying rule: test.py; took: 0:00:00.000021
DEBUG: Trying rule: adb_unknown_command; took: 0:00:00.000025
DEBUG: Trying rule: ag_literal; took: 0:00:00.000010
DEBUG: Trying rule: aws_cli; took: 0:00:00.000029
DEBUG: Trying rule: az_cli; took: 0:00:00.000010
DEBUG: Trying rule: brew_cask_dependency; took: 0:00:00.000009
DEBUG: Trying rule: brew_install; took: 0:00:00.000002
DEBUG: Trying rule: brew_link; took: 0:00:00.000010
DEBUG: Trying rule: brew_reinstall; took: 0:00:00.000009
DEBUG: Trying rule: brew_uninstall; took: 0:00:00.000008
DEBUG: Trying rule: brew_unknown_command; took: 0:00:00.000002
DEBUG: Trying rule: brew_update_formula; took: 0:00:00.000028
DEBUG: Trying rule: cargo; took: 0:00:00.000002
DEBUG: Trying rule: cargo_no_command; took: 0:00:00.000009
DEBUG: Trying rule: cat_dir; took: 0:00:00.000010
DEBUG: Trying rule: cd_correction; took: 0:00:00.000010
DEBUG: Trying rule: cd_mkdir; took: 0:00:00.000009
DEBUG: Trying rule: cd_parent; took: 0:00:00.000002
DEBUG: Trying rule: chmod_x; took: 0:00:00.000002
DEBUG: Trying rule: composer_not_command; took: 0:00:00.000030
DEBUG: Trying rule: cp_create_destination; took: 0:00:00.000009
DEBUG: Trying rule: cp_omitting_directory; took: 0:00:00.000009
DEBUG: Trying rule: cpp11; took: 0:00:00.000009
DEBUG: Trying rule: dirty_untar; took: 0:00:00.000008
DEBUG: Trying rule: dirty_unzip; took: 0:00:00.000009
DEBUG: Trying rule: django_south_ghost; took: 0:00:00.000002
DEBUG: Trying rule: django_south_merge; took: 0:00:00.000001
DEBUG: Trying rule: docker_image_being_used_by_container; took: 0:00:00.000009
DEBUG: Trying rule: docker_login; took: 0:00:00.000008
DEBUG: Trying rule: docker_not_command; took: 0:00:00.000008
DEBUG: Trying rule: fab_command_not_found; took: 0:00:00.000022
DEBUG: Trying rule: fix_alt_space; took: 0:00:00.000003
DEBUG: Trying rule: fix_file; took: 0:00:00.000016
DEBUG: Trying rule: gem_unknown_command; took: 0:00:00.000032
DEBUG: Trying rule: git_add; took: 0:00:00.000008
DEBUG: Trying rule: git_add_force; took: 0:00:00.000007
DEBUG: Trying rule: git_bisect_usage; took: 0:00:00.000008
DEBUG: Trying rule: git_branch_delete; took: 0:00:00.000007
DEBUG: Trying rule: git_branch_delete_checked_out; took: 0:00:00.000008
DEBUG: Trying rule: git_branch_exists; took: 0:00:00.000027
DEBUG: Trying rule: git_branch_list; took: 0:00:00.000022
DEBUG: Trying rule: git_checkout; took: 0:00:00.000008
DEBUG: Trying rule: git_commit_amend; took: 0:00:00.000008
DEBUG: Trying rule: git_commit_reset; took: 0:00:00.000007
DEBUG: Trying rule: git_diff_no_index; took: 0:00:00.000007
DEBUG: Trying rule: git_diff_staged; took: 0:00:00.000007
DEBUG: Trying rule: git_fix_stash; took: 0:00:00.000021
DEBUG: Trying rule: git_flag_after_filename; took: 0:00:00.000007
DEBUG: Trying rule: git_help_aliased; took: 0:00:00.000007
DEBUG: Trying rule: git_merge; took: 0:00:00.000007
DEBUG: Trying rule: git_merge_unrelated; took: 0:00:00.000007
DEBUG: Trying rule: git_not_command; took: 0:00:00.000007
DEBUG: Trying rule: git_pull; took: 0:00:00.000022
DEBUG: Trying rule: git_pull_clone; took: 0:00:00.000007
DEBUG: Trying rule: git_pull_uncommitted_changes; took: 0:00:00.000008
DEBUG: Trying rule: git_push; took: 0:00:00.000007
DEBUG: Trying rule: git_push_different_branch_names; took: 0:00:00.000007
DEBUG: Trying rule: git_push_pull; took: 0:00:00.000007
DEBUG: Trying rule: git_push_without_commits; took: 0:00:00.000007
DEBUG: Trying rule: git_rebase_merge_dir; took: 0:00:00.000008
DEBUG: Trying rule: git_rebase_no_changes; took: 0:00:00.000007
DEBUG: Trying rule: git_remote_delete; took: 0:00:00.000008
DEBUG: Trying rule: git_remote_seturl_add; took: 0:00:00.000007                                                                                                     [47/10000]
DEBUG: Trying rule: git_rm_local_modifications; took: 0:00:00.000008
DEBUG: Trying rule: git_rm_recursive; took: 0:00:00.000008
DEBUG: Trying rule: git_rm_staged; took: 0:00:00.000007
DEBUG: Trying rule: git_stash; took: 0:00:00.000007
DEBUG: Trying rule: git_tag_force; took: 0:00:00.000007
DEBUG: Trying rule: git_two_dashes; took: 0:00:00.000007
DEBUG: Trying rule: go_run; took: 0:00:00.000009
DEBUG: Trying rule: go_unknown_command; took: 0:00:00.000008
DEBUG: Trying rule: gradle_no_task; took: 0:00:00.000009
DEBUG: Trying rule: gradle_wrapper; took: 0:00:00.000010
DEBUG: Trying rule: grep_arguments_order; took: 0:00:00.000009
DEBUG: Trying rule: grep_recursive; took: 0:00:00.000009
DEBUG: Trying rule: grunt_task_not_found; took: 0:00:00.000009
DEBUG: Trying rule: gulp_not_task; took: 0:00:00.000008
DEBUG: Trying rule: has_exists_script; took: 0:00:00.000011
DEBUG: Trying rule: heroku_multiple_apps; took: 0:00:00.000009
DEBUG: Trying rule: heroku_not_command; took: 0:00:00.000010
DEBUG: Trying rule: hostscli; took: 0:00:00.000010
DEBUG: Trying rule: ifconfig_device_not_found; took: 0:00:00.000009
DEBUG: Trying rule: java; took: 0:00:00.000009
DEBUG: Trying rule: javac; took: 0:00:00.000009
DEBUG: Trying rule: lein_not_task; took: 0:00:00.000009
DEBUG: Trying rule: ln_no_hard_link; took: 0:00:00.000005
DEBUG: Trying rule: ln_s_order; took: 0:00:00.000003
DEBUG: Trying rule: ls_all; took: 0:00:00.000009
DEBUG: Trying rule: ls_lah; took: 0:00:00.000007
DEBUG: Trying rule: man; took: 0:00:00.000009
DEBUG: Trying rule: mercurial; took: 0:00:00.000008
DEBUG: Trying rule: mkdir_p; took: 0:00:00.000002
DEBUG: Trying rule: mvn_no_command; took: 0:00:00.000011
DEBUG: Trying rule: mvn_unknown_lifecycle_phase; took: 0:00:00.000008
DEBUG: Trying rule: no_such_file; took: 0:00:00.000615
DEBUG: Trying rule: npm_missing_script; took: 0:00:00.000014
DEBUG: Trying rule: npm_run_script; took: 0:00:00.000010
DEBUG: Trying rule: npm_wrong_command; took: 0:00:00.000010
DEBUG: Trying rule: open; took: 0:00:00.000011
DEBUG: Trying rule: php_s; took: 0:00:00.000011
DEBUG: Trying rule: pip_install; took: 0:00:00.000010                                                                                                                [9/10000]
DEBUG: Trying rule: pip_unknown_command; took: 0:00:00.000010
DEBUG: Trying rule: port_already_in_use; took: 0:00:00.000453
DEBUG: Trying rule: prove_recursively; took: 0:00:00.000031
DEBUG: Trying rule: pyenv_no_such_command; took: 0:00:00.000011
DEBUG: Trying rule: python_command; took: 0:00:00.000004
DEBUG: Trying rule: python_execute; took: 0:00:00.000010
DEBUG: Trying rule: quotation_marks; took: 0:00:00.000002
DEBUG: Trying rule: react_native_command_unrecognized; took: 0:00:00.000010
DEBUG: Trying rule: remove_shell_prompt_literal; took: 0:00:00.000002
DEBUG: Trying rule: remove_trailing_cedilla; took: 0:00:00.000002
DEBUG: Trying rule: rm_dir; took: 0:00:00.000002
DEBUG: Trying rule: scm_correction; took: 0:00:00.000009
DEBUG: Trying rule: sed_unterminated_s; took: 0:00:00.000025
DEBUG: Trying rule: sl_ls; took: 0:00:00.000002
DEBUG: Trying rule: ssh_known_hosts; took: 0:00:00.000009
DEBUG: Trying rule: sudo; took: 0:00:00.000007
DEBUG: Trying rule: sudo_command_from_user_path; took: 0:00:00.000028
DEBUG: Trying rule: switch_lang; took: 0:00:00.000039
DEBUG: Trying rule: systemctl; took: 0:00:00.000010
DEBUG: Trying rule: terraform_init; took: 0:00:00.000027
DEBUG: Trying rule: tmux; took: 0:00:00.000009
DEBUG: Trying rule: touch; took: 0:00:00.000009
DEBUG: Trying rule: tsuru_login; took: 0:00:00.000011
DEBUG: Trying rule: tsuru_not_command; took: 0:00:00.000008
DEBUG: Trying rule: unknown_command; took: 0:00:00.000102
DEBUG: Trying rule: unsudo; took: 0:00:00.000003
DEBUG: Trying rule: vagrant_up; took: 0:00:00.000012
DEBUG: Trying rule: whois; took: 0:00:00.000011
DEBUG: Trying rule: workon_doesnt_exists; took: 0:00:00.000009
DEBUG: Trying rule: yarn_alias; took: 0:00:00.000010
DEBUG: Trying rule: yarn_command_not_found; took: 0:00:00.000009
DEBUG: Trying rule: yarn_command_replaced; took: 0:00:00.000011
DEBUG: Trying rule: yarn_help; took: 0:00:00.000010
DEBUG: Trying rule: docker_containers; took: 0:00:00.000008
DEBUG: Trying rule: mpv_yt; took: 0:00:00.000009
DEBUG: Trying rule: terraform_init.bak; took: 0:00:00.000006
DEBUG: Trying rule: terraform_init; took: 0:00:00.000010
DEBUG: Trying rule: man_no_space; took: 0:00:00.000002
DEBUG: Trying rule: no_command; took: 0:00:00.004730
git c -m a commit message here [enter/_/_/ctrl+c]
DEBUG: PYTHONIOENCODING: utf-8
DEBUG: Total took: 0:00:03.924391
error: pathspec 'commit' did not match any file(s) known to git
error: pathspec 'message' did not match any file(s) known to git
error: pathspec 'here' did not match any file(s) known to git
$
```

> If the bug only appears with a specific application, the output of that application and its version:

It seems to be an issue with anything that hooks on the no_command rule.

**Comment by scorphus** [comment] 2020-05-02 22:27
Quite incredible this issue took so long to show up. I can reproduce it. Fix is on its way.

Thanks for reporting it!

**Comment by scorphus** [comment] 2021-08-02 22:52
Actually, this is a duplicate of #720.

**Closed by scorphus** 2021-08-02 22:52 UTC
Labels: WIP, bug, next release
