### ISSUE TITLE
alias fuck="fuck -y" causes error when sourcing .zshrc

### ISSUE THREAD

**Issue by orthodoX** [nvbn/thefuck#1071] opened 2020-03-27 16:36 UTC
* The output of `thefuck --version`

`The Fuck 3.30 using Python 3.8.2 and ZSH 5.8`

* My system:

` macOS Catalina 10.15.4`

* How to reproduce the bug:

Update the `.zshrc` file. When I try to do a `source ~/.zshrc` I get the following error:
```
(eval):2: defining function based on alias `fuck'
(eval):2: parse error near `()'
```
The error is caused by `eval "$(thefuck --alias)"` line in the file. Note: When I for example open a new tab in the terminal after updating the config zsh initializes normally without errors.

* The output of The Fuck with `THEFUCK_DEBUG=true`

Same as ☝️

**Comment by scorphus** [comment] 2020-03-29 12:59
I could not reproduce the bug. What is the output of `thefuck --alias`? It should be as follows:

```
            fuck () {
                TF_PYTHONIOENCODING=$PYTHONIOENCODING;
                export TF_SHELL=zsh;
                export TF_ALIAS=fuck;
                TF_SHELL_ALIASES=$(alias);
                export TF_SHELL_ALIASES;
                TF_HISTORY="$(fc -ln -10)";
                export TF_HISTORY;
                export PYTHONIOENCODING=utf-8;
                TF_CMD=$(
                    thefuck THEFUCK_ARGUMENT_PLACEHOLDER $@
                ) && eval $TF_CMD;
                unset TF_HISTORY;
                export PYTHONIOENCODING=$TF_PYTHONIOENCODING;
                test -n "$TF_CMD" && print -s $TF_CMD
            }
```

**Comment by orthodoX** [comment] 2020-03-29 13:34
Yes It's exactly like that. I found what was causing the error. Below that in the config I had this `alias fuck="fuck -y"` And that was causing the problem 🙄 My bad. Is there a proper way to alias `fuck` to `fuck -y`?

**Comment by scorphus** [comment] 2020-03-29 13:50
Glad you found the issue \o/

How about:

```
john@host ~ % grep fuck .zshrc
eval $(thefuck --alias __fuck)
alias fuck="__fuck -y"
john@host ~ % echoo ok
zsh: command not found: echoo
john@host ~ % fuck
echo ok
ok
john@host ~ % 
```

**Comment by scorphus** [comment] 2020-03-29 13:55
The following works for me as well:

```
eval $(thefuck --alias fuck)
alias fuck="fuck -y"
```

ps.: sorry, I close the issue accidentally (cmd+shift+enter – I thought I was in vscode 🤪)

**Comment by scorphus** [comment] 2020-03-29 13:59
This:

```
john@host ~ % grep fuck .zshrc
eval $(thefuck --alias)
alias fuck="fuck -y"
```

Also works:

```
john@host ~ % echoo ok
zsh: command not found: echoo
john@host ~ % fuck
echo ok
ok
```

**Comment by scorphus** [comment] 2020-03-29 14:02
Ah, `.zshrc` can only be `source`’d when the function is defined as `__fuck` and the alias uses it – a.k.a. [my first suggestion](https://github.com/nvbn/thefuck/issues/1071#issuecomment-605638913).

**Comment by orthodoX** [comment] 2020-03-29 14:05
@scorphus Exactly, that's what I wanted to write now. I renamed to issue to properly address the problem. And just to confirm the solution is:

```sh
eval $(thefuck --alias)
alias fuck="__fuck -y"
```
Thanks so much for helping out with this one!

**Closed** 2020-03-29 14:05 UTC
