### ISSUE TITLE
Real question :(

### ISSUE THREAD

**Issue by dontknowhy** [nvbn/thefuck#1263] opened 2022-01-11 11:40 UTC
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):
YES,THEFUCK CAN'T OUTPUT ANY INFORMATION
GNU bash，版本 5.1.16(1)-release (aarch64-unknown-linux-gnu)（Thefuck's crash ≠ bash's language setting ） 

Your system (Debian 7, ArchLinux, Windows, etc.):

    Debian sid (IN PROOT,AND IN TERMUX)

How to reproduce the bug:

    type 'thefuck'
And done

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

  Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/psutil/_common.py", line 397, in wrapper
    return cache[key]
KeyError: (('/proc',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 303, in <module>
    set_scputimes_ntuple("/proc")
  File "/usr/lib/python3/dist-packages/psutil/_common.py", line 399, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 270, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/usr/lib/python3/dist-packages/psutil/_common.py", line 711, in open_binary
    return open(fname, "rb", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/stat'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1661, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1879, in create_time
    bt = BOOT_TIME or boot_time()
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1580, in boot_time
    with open_binary(path) as f:
  File "/usr/lib/python3/dist-packages/psutil/_common.py", line 711, in open_binary
    return open(fname, "rb", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/thefuck", line 9, in <module>
    from thefuck.entrypoints.main import main
  File "/usr/share/thefuck/thefuck/entrypoints/main.py", line 11, in <module>
    from ..shells import shell  # noqa: E402
  File "/usr/share/thefuck/thefuck/shells/__init__.py", line 52, in <module>
    shell = _get_shell_from_env() or _get_shell_from_proc()
  File "/usr/share/thefuck/thefuck/shells/__init__.py", line 45, in _get_shell_from_proc
    proc = proc.parent()
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 554, in parent
    ctime = self.create_time()
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 717, in create_time
    self._create_time = self._proc.create_time()
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1663, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: (pid=26745, name='thefuck')

If the bug only appears with a specific application, the output of that application and its version:

    no,it crash every startup

Anything else you think is relevant:

/proc can't be access

**Comment by scorphus** [comment] 2022-01-11 13:26
Duplicate of #1112

**Closed by scorphus** 2022-01-11 13:26 UTC
