### ISSUE TITLE
Red color not reset when no fucks were given

### ISSUE THREAD

**Issue by SijmenSchoon** [nvbn/thefuck#815] opened 2018-05-17 11:55 UTC
**The output of `thefuck --version` (something like `The Fuck 3.1 using Python 3.5.0`):**

    The Fuck 3.26 using Python 3.6.3

**Your shell and its version (`bash`, `zsh`, *Windows PowerShell*, etc.):**

Windows PowerShell

**Your system (Debian 7, ArchLinux, Windows, etc.):**

Windows

**How to reproduce the bug:**

Force a "no fucks given" output (by putting it after a successful command or something)

![image](https://user-images.githubusercontent.com/345785/40175872-dd8a5124-59d9-11e8-9bfb-99f9d7e4b9ef.png)

**The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):**

_not sure how to do this in PowerShell, but it shouldn't be that relevant_

**Comment by MattKotsenas** [comment] 2018-06-11 20:07
Duplicate of #772, fixed by #805.

**Comment by scorphus** [comment] 2018-06-12 09:48
Thanks for the comment, @MattKotsenas. Thanks @afwilkin for the fix. Closing this one.

**Closed by scorphus** 2018-06-12 09:48 UTC
Labels: windows
