### ISSUE TITLE
exception while "run fuck second time for configuring it automatically."

### ISSUE THREAD

**Issue by z3ntu** [nvbn/thefuck#658] opened 2017-06-08 20:26 UTC
```
luca@g550jk ~> fuck
Seems like fuck alias isn't configured!
Please put eval (thefuck --alias | tr '
' ';') in your ~/.config/fish/config.fish and apply changes with fish or restart your shell.
Or run fuck second time for configuring it automatically.
More details - https://github.com/nvbn/thefuck#manual-installation
luca@g550jk ~> fuck
Traceback (most recent call last):
  File "/usr/bin/fuck", line 11, in <module>
    load_entry_point('thefuck==3.18', 'console_scripts', 'fuck')()
  File "/usr/lib/python3.6/site-packages/thefuck/not_configured.py", line 80, in main
    elif _is_second_run():
  File "/usr/lib/python3.6/site-packages/thefuck/not_configured.py", line 40, in _is_second_run
    if not tracker_path.exists() or not shell.get_history()[-1] == 'fuck':
IndexError: list index out of range
luca@g550jk ~> thefuck --version
The Fuck 3.18 using Python 3.6.1
luca@g550jk ~> lsb_release -d
Description:    Arch Linux
luca@g550jk ~> echo $SHELL
/usr/bin/fish
luca@g550jk ~> fish --version
fish, version 2.5.0
```

**Comment by MelvIsntNormal** [comment] 2017-07-12 07:58
The history file for fish is no longer located in `.config/fish`, It's been moved to `.local/share/fish`. See [this commit](https://github.com/fish-shell/fish-shell/commit/b13f0701a45f45568060d7dd7a5fed1052e9be60).

**Comment by babakness** [comment] 2017-08-16 05:11
same error

**Comment by nvbn** [comment] 2017-08-16 09:29
Fixed in 3.20

**Comment by scorphus** [comment] 2017-10-04 17:57
Confirmed it's fixed. Thanks, @nvbn

**Comment by z3ntu** [comment] 2017-10-04 18:02
Why does the script add
```
eval (thefuck --alias | tr '
' ';')
```
to the fish config when the [wiki](https://github.com/nvbn/thefuck/wiki/Shell-aliases#fish) says something else
```
thefuck --alias | source 
```
?

**Comment by scorphus** [comment] 2017-10-04 23:03
It should be `eval (thefuck --alias | tr '\n' ';')` but the `\n` wasn't escaped. This can be easily fixed.

Are you interested? hint: https://hacktoberfest.digitalocean.com/

**Comment by z3ntu** [comment] 2017-10-05 05:44
@scorphus And what's the reason it's not `thefuck --alias | source` as it 1. looks nicer and 2. is shorter and works the same way?
And yes, I will do a PR for this :)

**Comment by scorphus** [comment] 2017-10-06 04:11
Because that nice and short trick of yours didn't occur to me at all! And now, after reading `eval`'s source code more closely, I can see that, in the end, it pipes to `source`.

Good job!

LGTM 👍

**Comment by scorphus** [comment] 2017-10-06 04:12
Also kudos for the commit message! 😉

**Closed** 2017-10-08 14:18 UTC
Labels: hacktoberfest
