### ISSUE TITLE
Warnings when using thefuck

### ISSUE THREAD

**Issue by LoZeno** [nvbn/thefuck#588] opened 2017-01-10 23:32 UTC
WARNING: Token 'COND_ERROR' defined, but not used
WARNING: There is 1 unused token
Unable to create '/usr/local/lib/python3.4/dist-packages/bashlex/parsetab.py'
[Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/bashlex/parsetab.py'

The above lines appear everytime I launch a shell, and everytime I use thefuck

**Comment by bil-elmoussaoui** [comment] 2017-01-11 01:05
Just run `sudo thefuck` one time, and the file will be created which will fix your issue. But it would be better if this can be fixed upstream (by bashlex)

**Comment by josephfrazier** [comment] 2017-01-11 04:20
The `WARNING` lines are caused by https://github.com/idank/bashlex/issues/20

The other lines are a separate matter. It could be fixed by changing `bashlex` so that it does not try to create `parsetab.py` (see https://github.com/dabeaz/ply/issues/79#issuecomment-243572084), but after some informal testing, I'm worried this might make `thefuck` slower, since it would be rebuilding the parser table on every invocation, rather than loading from `parsetab.py`.

Perhaps a better solution would be to make it so that `thefuck` can tell `bashlex` to put the `parsetab.py` file in `~/.config/thefuck/`.

**Comment by nvbn** [comment] 2017-01-11 12:13
@josephfrazier we actually should stop using bashlex because of [gpl license](https://github.com/idank/bashlex/blob/master/LICENSE) of it.

**Comment by nvbn** [comment] 2017-01-11 14:13
@LoZeno try 3.14

**Comment by josephfrazier** [comment] 2017-01-11 18:09
@nvbn Oops, I wasn't aware of the licensing conflict. Sorry about that! I'll open a new issue for finding an alternative solution to https://github.com/nvbn/thefuck/pull/580

**Closed** 2017-03-13 16:24 UTC
