### ISSUE TITLE
Receiving "command not found" on configuration

### ISSUE THREAD

**Issue by paige404** [nvbn/thefuck#499] opened 2016-04-28 15:23 UTC
Tested in my shell on Xubuntu 14.04:

``` bash
♥ mhausman@Quasit:~ ‽ thefuck --alias
alias fuck='TF_CMD=$(TF_ALIAS=fuck PYTHONIOENCODING=utf-8 TF_SHELL_ALIASES=$(alias) thefuck $(fc -ln -1)) && eval $TF_CMD && history -s $TF_CMD'
♥ mhausman@Quasit:~ ‽ eval "$(thefuck --alias)"
: command not found
```

Note that it functions oddly afterwards. For instance, after running I did the following:

``` bash
♥ mhausman@Quasit:~ ‽ gdit
No command 'gdit' found, did you mean:
 Command 'dgit' from package 'dgit' (universe)
 Command 'git' from package 'git' (main)
 Command 'gedit' from package 'gedit' (main)
 Command 'gdis' from package 'gdis' (universe)
 Command 'edit' from package 'mime-support' (main)
gdit: command not found
♥ mhausman@Quasit:~ ‽ fuck
gedit [enter/↑/↓/ctrl+c]
```

It _looks_ like it's working. But when I hit enter, the command it actually ran was `gedit ^[[0m`. I'm not sure if that's related, but it seemed worth mentioning.

**Comment by mdhausman** [comment] 2016-05-16 22:41
So I guess this is just more of the weird whitespace handling. We can add xfce-terminal to the list of terminals that aren't being handled properly.

```
♥ mhausman:~/<snip> ‽ checkout master
checkout: command not found
♥ mhausman:~/<snip> ‽ fuck
git checkout master [enter/↑/↓/ctrl+c]
error: pathspec '' did not match any file(s) known to git.
```

**Comment by scorphus** [comment] 2016-05-18 02:19
Hi! Please paste the output of the two commands below:
```
thefuck --version
```
```fish
python -c 'from thefuck.shells import shell; print(shell.__class__)'
```
Thanks!

**Comment by mdhausman** [comment] 2016-05-18 16:31
```
♥ mhausman:~ ‽ thefuck --version
The Fuck 3.9 using Python 2.7.6
♥ mhausman:~ ‽ python -c 'from thefuck.shells import shell; print(shell.__class__)'
<class 'thefuck.shells.bash.Bash'>
```

**Comment by scorphus** [comment] 2016-05-19 04:14
@mdhausman, this is what I got on a fresh Xubuntu 14.04 install:

![thefuck1](https://cloud.githubusercontent.com/assets/2112697/15382244/9ad07098-1d5e-11e6-8604-9d321989d1ee.png)

![thefuck2](https://cloud.githubusercontent.com/assets/2112697/15382248/a8f3fc12-1d5e-11e6-9dba-6c211de5f1c3.png)

What is your Bash version? And can you share your `~/.bashrc` file?

Thanks!

**Comment by scorphus** [comment] 2016-05-19 04:22
Also germane to the discussion:
```
vagrant@vagrant-VBox:~$ apt-cache show xfce4-terminal | grep -E 'Pa|In|Ve'
Package: xfce4-terminal
Installed-Size: 2071
Version: 0.6.3-1ubuntu1
```

**Comment by mdhausman** [comment] 2016-05-20 21:52
```
♥ mhausman:~ ‽ bash --version 
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
♥ mhausman:~ ‽ apt-cache show xfce4-terminal | grep -E 'Pa|In|Ve'
Package: xfce4-terminal
Installed-Size: 2071
Version: 0.6.3-1ubuntu1
```

**Comment by scorphus** [comment] 2016-05-21 01:31
Thanks for that information. How about your .bashrc? Or the script that
evals the fuck function. Thanks.
Em 20/05/2016 18:53, "Maura Hausman" <notifications@github.com> escreveu:

**Comment by ACinnamonUserInUK** [comment] 2016-07-25 07:27
I am getting the same problem in both Gnome terminal and XFCE terminal (both on Mint). The problem occurred after I edited by /etc/environment, which contains the PATH variable.

Also: we've got a duplicate of this issue [here (#502)](url=https://github.com/nvbn/thefuck/issues/502).

**Closed** 2019-12-29 21:51 UTC
