### ISSUE TITLE
Can't use with out of range(128) characters

### ISSUE THREAD

**Issue by blakeembrey** [nvbn/thefuck#398] opened 2015-10-30 23:36 UTC
I was using a branch with `�` in the name. When I `git push` I correct it so that it'll push with the git suggested prompt. It doesn't work.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/thefuck/3.1/libexec/bin/thefuck", line 9, in <module>
    load_entry_point('thefuck==3.1', 'console_scripts', 'thefuck')()
  File "/usr/local/Cellar/thefuck/3.1/libexec/lib/python2.7/site-packages/thefuck/main.py", line 77, in main
    fix_command()
  File "/usr/local/Cellar/thefuck/3.1/libexec/lib/python2.7/site-packages/thefuck/main.py", line 28, in fix_command
    selected_command = select_command(corrected_commands)
  File "/usr/local/Cellar/thefuck/3.1/libexec/lib/python2.7/site-packages/thefuck/ui.py", line 106, in select_command
    logs.confirm_text(selector.value)
  File "/usr/local/Cellar/thefuck/3.1/libexec/lib/python2.7/site-packages/thefuck/logs.py", line 61, in confirm_text
    blue=color(colorama.Fore.BLUE)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position 36: ordinal not in range(128)
```

**Comment by mcarton** [comment] 2015-10-31 23:05
Are you using The Fuck with python 2? If so, python 3 has much less Unicode problems, you should try it.

**Comment by blakeembrey** [comment] 2015-11-01 18:34
@mcarton Definitely python 2. I probably won't end up aliasing `python3` over `python`, there's some things in node that fail to build with `python3`.

**Comment by mcarton** [comment] 2015-11-01 18:39
You can install The Fuck with python 3 without affecting any other program. You'd just have to use `python3 setup.py install`/`pip3 install thefuck`/`whatever-you-used-to-install-The-Fuck-but-with-a-3-in-the-name`. Python 2 and Python 3 live very well together.

@nvbn : by the way, how about using python3 if available in the `install.sh` script ?

**Comment by nvbn** [comment] 2015-11-02 10:43
@mcarton I'll try to update script.

@blakeembrey btw, fix for the problem will be in the next release.

**Comment by nvbn** [comment] 2015-11-03 09:45
@blakeembrey try to update to thefuck 3.2, probably fixed.

**Comment by blakeembrey** [comment] 2015-11-04 23:19
@nvbn Sorry for the delay, looks like it works. Doesn't work with the ZSH shortcut I'm using from https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/thefuck/thefuck.plugin.zsh#L9-L17 though.

**Comment by scorphus** [comment] 2015-11-04 23:49
I can reproduce this and other cases. I'm investigating it and might soon submit a PR.

**Comment by scorphus** [comment] 2015-11-06 22:13
@blakeembrey: Are you still using Python 2?

@all: there are still some problems with Python2 and Unicode (i.e. `thefuck echoo café`). I can fix that. But should I endeavor in such adventure? What do you guys think?

**Comment by blakeembrey** [comment] 2015-11-06 22:17
@scorphus Yes, it's still Python 2 by default. I'm just using `brew` for this, and some native deps in node require Python 2 so it's unlikely I'll update the alias.

**Comment by mcarton** [comment] 2015-11-06 22:22
> I can fix that. But should I endeavor in such adventure?

Is it worth it? Would that mean add the `u` prefix to all string literals in the source code? What is the point of using Python 2 if Python 3 is available? Is there anything in The Fuck that is not compatible with Python 3? Is there any platform where Python 2 is available, but Python 3 is not?
Python 3 just works. I don't think Python 2 should be a time consuming problem in 2015.
I vote for updating the install script to use Python 3 and advise using it on the README.

(I think that most people just use Python 2 when Python 3 would be perfectly fine is because `/usr/bin/python` defaults to Python 2 on most platforms, and `python` 1 character less than `python3`).

**Comment by cintiadr** [comment] 2015-11-09 00:18
Not really sure why, got similar error message on OSX:

```
~/checkouts/configuration (MIN-338_new_jobs:git) $ fuck
Traceback (most recent call last):
  File "/usr/local/bin/thefuck", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/thefuck/main.py", line 77, in main
    fix_command()
  File "/usr/local/lib/python2.7/site-packages/thefuck/main.py", line 28, in fix_command
    selected_command = select_command(corrected_commands)
  File "/usr/local/lib/python2.7/site-packages/thefuck/ui.py", line 106, in select_command
    logs.confirm_text(selector.value)
  File "/usr/local/lib/python2.7/site-packages/thefuck/logs.py", line 61, in confirm_text
    blue=color(colorama.Fore.BLUE)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2191' in position 45: ordinal not in range(128)
```

I added `export PYTHONIOENCODING=utf-8` to my .profile, and not it doesn't complain anymore, just works. 

Pip tells me it has installed fuck 3.2

**Comment by scorphus** [comment] 2015-11-09 19:21
I think that there is a real share of Python 2 users, whether we like it or not. And I think we can't just leave them with a buggy software if that's amendable. I don't think we should turn our backs to Python 2.

**Comment by mcarton** [comment] 2015-11-09 19:53
I did not say we should not fix it. I said the fix was simply to use Python 3.

**Comment by scorphus** [comment] 2015-11-09 20:33
Ah, okay. Your rhetorical questions led me to think otherwise :smile:

I can turn myself to the fixing of it. #handson

**Comment by nvbn** [comment] 2015-11-10 10:37
@mcarton I guess it'll be better to continue support of python 2.7. In semi-popular ubuntu 12.04 only 2.7 and 3.2 (not supported by thefuck) are availble.

**Comment by WANG-lp** [comment] 2015-11-18 08:07
@cintiadr Thanks. It is ok after I added `export PYTHONIOENCODING=utf-8` in my `.zshrc`

**Comment by lovedboy** [comment] 2015-11-18 15:20
nice:)

**Comment by lovedboy** [comment] 2015-11-18 15:36
@nvbn Python2.7 and have merged the newest master code

```
⇒  git commt -am "哈哈"
git: 'commt' is not a git command. See 'git --help'.

Did you mean this?
	commit
zhuo@lovedboy:~/Desktop/git/thefuck|master⚡
⇒  fuck
[WARN] Rule dry:
Traceback (most recent call last):
  File "/Users/zhuo/git/thefuck/thefuck/types.py", line 222, in is_match
    if compatibility_call(self.match, command):
  File "/Users/zhuo/git/thefuck/thefuck/utils.py", line 255, in compatibility_call
    return fn(*args)
  File "/Users/zhuo/git/thefuck/thefuck/rules/dry.py", line 2, in match
    split_command = command.script_parts
  File "/Users/zhuo/git/thefuck/thefuck/types.py", line 35, in script_parts
    self, sys.exc_info()))
  File "/Users/zhuo/git/thefuck/thefuck/types.py", line 48, in __repr__
    self.script, self.stdout, self.stderr)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 15-16: ordinal not in range(128)
----------------------------
```

```
⇒  echo $PYTHONIOENCODING
utf-8
```

**Comment by scorphus** [comment] 2016-05-18 02:43
@lovedboy: Any update on this?

**Comment by lovedboy** [comment] 2016-05-18 02:46
@scorphus works nice now.

**Closed** 2017-03-13 22:53 UTC
Labels: next release
