### ISSUE TITLE
Buggy o/p: When 'fuck' is coupled with 'rmdir'

### ISSUE THREAD

**Issue by ja5h** [nvbn/thefuck#152] opened 2015-05-01 10:42 UTC
![screenshot from 2015-05-01 16 06 38](https://cloud.githubusercontent.com/assets/5393353/7429258/1ded08a4-f01c-11e4-94fe-e782bf216950.png)

As seen from the above picture, 'rmdir' causes fuck to behave funny. 

After deleting a directory created using fuck if I try to recreate it, it does recreate it but gives the output on the console as 'No fuck given'.

This happens repeatedly everytime the same set of statements is executed. 

*(PS: I am a novice student so please bear with me if I make a few noob mistakes.)*

**Comment by pranav15197** [comment] 2015-05-01 15:49
The problem seems to be with the history class, as on commenting out the following in the get_command function the issue disappears
```  
#if script == 'fuck' or script == history.last_script:
#    script = history.last_fixed_script or history.last_script
```

**Comment by scorphus** [comment] 2015-05-01 17:05
Strange. It works just fine for me, I couldn't reproduce:

![screen shot 2015-05-01 at 2 00 47 pm](https://cloud.githubusercontent.com/assets/2112697/7433732/a5a69240-f00a-11e4-81c5-fdb20a958f38.png)

**Comment by pranav15197** [comment] 2015-05-01 17:05
This seems to be a more general issue, as same bug appears if you repeat any wrong command -
for example
![selection_003](https://cloud.githubusercontent.com/assets/4546718/7433757/49e67ce8-f052-11e4-99bf-2e733b8db5b2.png)

**Comment by pranav15197** [comment] 2015-05-01 17:10
changing 
```
if script == 'fuck' or script == history.last_script:
       script = history.last_fixed_script or history.last_script
```
to
```
if script == 'fuck' or script == history.last_script:
       script = history.last_script or history.last_fixed_script
```
fixes the issue

**Comment by scorphus** [comment] 2015-05-01 17:12
It seems to be a problem with Bash. It works nice with Fish:

![screen shot 2015-05-01 at 2 09 33 pm](https://cloud.githubusercontent.com/assets/2112697/7433860/fb6585e6-f00b-11e4-90c1-8f21502c456e.png)

**Comment by ja5h** [comment] 2015-05-01 17:14
@pranav15197 The fix worked on my system too. Thanks.

**Comment by scorphus** [comment] 2015-05-01 17:17
What shell are you using? What version of TheFuck? It works for me in Bash too:

![screen shot 2015-05-01 at 2 16 04 pm](https://cloud.githubusercontent.com/assets/2112697/7433964/c24e69fc-f00c-11e4-81da-774c6bdea1b6.png)

**Comment by pranav15197** [comment] 2015-05-01 17:21
I cloned the repo today and installed it for development, the version = 1.32 on the setup.py file

**Comment by ja5h** [comment] 2015-05-01 17:25
Same as @pranav15197 . Installed today, version 1.32.

**Comment by nvbn** [comment] 2015-05-02 02:45
Yep, repeats for me with:
```bash
➜  cd dummy 
autoenv_cd:cd:2: no such file or directory: dummy
➜  fuck
mkdir -p dummy && cd dummy [enter/ctrl+c]
➜  cd ..
➜  rm -rf dummy 
➜  cd dummy
autoenv_cd:cd:2: no such file or directory: dummy
➜  fuck
No fuck given
```

**Comment by scorphus** [comment] 2015-05-02 02:57
Oh! It works for me:

```bash
»»»» cd dummy
cd: The directory 'dummy' does not exist
»»»» fuck
mkdir -p dummy && cd dummy
»»»» cd ..
»»»» rm -rf dummy
»»»» cd dummy
cd: The directory 'dummy' does not exist
»»»» fuck
mkdir -p dummy && cd dummy
»»»» pip freeze | grep thefuck
thefuck==1.32
»»»» fish --version
fish, version 2.1.2
```

**Comment by scorphus** [comment] 2015-05-02 02:59
It also works with bash:

```bash
bash-4.3$ ls
bash-4.3$ cd dummy
bash: cd: dummy: No such file or directory
bash-4.3$ fuck
mkdir -p dummy && cd dummy
bash-4.3$ cd ..
bash-4.3$ rm -rf dummy
bash-4.3$ cd dummy
bash: cd: dummy: No such file or directory
bash-4.3$ fuck
mkdir -p dummy && cd dummy
bash-4.3$ pip freeze | grep thefuck
thefuck==1.32
bash-4.3$ bash --version
GNU bash, version 4.3.33(1)-release (x86_64-apple-darwin14.1.0)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by nvbn** [comment] 2015-05-02 03:05
@scorphus it repeats only in version from git.

And I almost know how to fix it =)

**Comment by scorphus** [comment] 2015-05-03 01:03
Oh, my bad. Sorry, I thought I was helping. I now confirm this issue.

**Comment by nvbn** [comment] 2015-05-04 03:02
Probably fixed in 1.35+

**Comment by scorphus** [comment] 2015-05-04 04:44
I confirm it is fixed in Fish and Bash. Thanks @nvbn!

**Closed** 2015-05-07 11:14 UTC

**Comment by ja5h** [comment] 2015-05-08 15:39
Thanks @nvbn :)
