### ISSUE TITLE
yarn "Did you mean" broke thefuck parser

### ISSUE THREAD

**Issue by Akiyamka** [nvbn/thefuck#1098] opened 2020-05-28 12:11 UTC
> The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    The Fuck 3.15 using Python 3.7.6

> Your system (Debian 7, ArchLinux, Windows, etc.):

    Fedora release 31 5.5.15-200.fc31.x86_64

> How to reproduce the bug:

1) mkdir fuck_bug
2) cd ./fuck_bug
3) create package.json with next content

```
{
  "name": "fuck_bug",
  "version": "1.0.0",
  "scripts": {
  	"release": "echo 'succsess'"
  },
  "main": "index.js",
  "license": "MIT"
}
```
4) yarn relese
5) fuck
```
Traceback (most recent call last):
  File "/usr/bin/thefuck", line 11, in <module>
    load_entry_point('thefuck==3.15', 'console_scripts', 'thefuck')()
  File "/usr/lib/python3.7/site-packages/thefuck/main.py", line 67, in main
    fix_command()
  File "/usr/lib/python3.7/site-packages/thefuck/main.py", line 31, in fix_command
    selected_command = select_command(corrected_commands)
  File "/usr/lib/python3.7/site-packages/thefuck/ui.py", line 70, in select_command
    selector = CommandSelector(corrected_commands)
  File "/usr/lib/python3.7/site-packages/thefuck/ui.py", line 33, in __init__
    self._commands = [next(self._commands_gen)]
  File "/usr/lib/python3.7/site-packages/thefuck/corrector.py", line 43, in organize_commands
    first_command = next(corrected_commands)
  File "/usr/lib/python3.7/site-packages/thefuck/corrector.py", line 74, in <genexpr>
    for corrected in rule.get_corrected_commands(command))
  File "/usr/lib/python3.7/site-packages/thefuck/types.py", line 240, in get_corrected_commands
    new_commands = self.get_new_command(command)
  File "/usr/lib/python3.7/site-packages/thefuck/rules/yarn_alias.py", line 12, in get_new_command
    fix = re.findall(r'Did you mean `yarn ([^`]*)`', command.stderr)[0]
IndexError: list index out of range
```

> The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):
   
command `export THEFUCK_DEBUG=true fuck` at last step print nothing

> If the bug only appears with a specific application, the output of that application and its version:

Yes it's happens only with yarn
```
yarn run v1.22.4
error Command "relese" not found. Did you mean "release"?
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Anything else you think is relevant:

    Shell: zsh 5.7.1

**Comment by scorphus** [comment] 2020-05-28 18:19
>    The Fuck 3.15 using Python 3.7.6

The current version is 3.30. Can you please update it and try again?

**Comment by Akiyamka** [comment] 2020-06-06 16:01
@scorphus for some reason in fedora repos 3.15 is last version (
https://pkgs.org/search/?q=thefuck

**Comment by divykj** [comment] 2020-06-11 05:43
```shell
~/Projects/Playground/fuck_bug
❯ fuck -v
The Fuck 3.30 using Python 3.8.3 and ZSH 5.8

~/Projects/Playground/fuck_bug
❯ yarn relese
yarn run v1.22.4
error Command "relese" not found. Did you mean "release"?
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

~/Projects/Playground/fuck_bug
❯ fuck
yarn release [enter/↑/↓/ctrl+c]
yarn run v1.22.4
$ echo 'succsess'
succsess
Done in 0.07s.
```

@Akiyamka I tried to reproduce this. Looks like it works in the latest version of thefuck.

**Comment by scorphus** [comment] 2020-06-15 15:08
Something seems not right on Fedora's side, unfortunately:

* https://bugzilla.redhat.com/show_bug.cgi?id=1576812
* https://release-monitoring.org/project/7893/

Closing this for now.

**Closed by scorphus** 2020-06-15 15:08 UTC
Labels: cannot reproduce
