### ISSUE TITLE
stdin and stdout don't match - oh-my-zsh (Windows)

### ISSUE THREAD

**Issue by dheerajpv** [nvbn/thefuck#1203] opened 2021-05-31 00:36 UTC
The output of `thefuck --version` (something like `The Fuck 3.1 using Python
3.5.0 and Bash 4.4.12(1)-release`):

    The Fuck 3.30 using Python 3.9.5 and ZSH 5.8

Your system (Debian 7, ArchLinux, Windows, etc.):

    Windows 10 (Git Bash with oh-my-zsh installed)

How to reproduce the bug:

- Install thefuck using `pip`. 
- Add thefuck plugin to `~/.zshrc`

The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):

```
c:\users\<user>\appdata\local\programs\python\python39\lib\site-packages\win_unicode_console\__init__.py:31: RuntimeWarning: sys.stdin.encoding == 'utf-8', whereas sys.stdout.encoding == 'cp1252', readline hook consumer may assume they are the same
  readline_hook.enable(use_pyreadline=use_pyreadline)
(eval):18: parse error near `^M'
```

Anything else you think is relevant:

I did read the powershell issue, (which did indeed work on powershell), but trying to fix it the same way (by setting `PYTHONIOENCODING` to "utf-8") does not fix the issue on zsh.

I am using Windows Terminal, if that is important information.

**Comment by scorphus** [comment] 2021-07-23 18:22
Duplicate of #1189

**Closed by scorphus** 2021-07-23 18:22 UTC
