### ISSUE TITLE
Re-license under WTFPL

### ISSUE THREAD

**Issue by sergei-ivanov** [nvbn/thefuck#59] opened 2015-04-20 14:24 UTC
I believe WTFPL licence might be quite appropriate for this project:
http://www.wtfpl.net/about/

**Comment by aspushkinus** [comment] 2015-04-20 17:26
I concur. Please change.

**Comment by nvbn** [comment] 2015-04-20 18:06
I think MIT is better =)
Also, duplicate of #27 and #5.

**Closed by nvbn** 2015-04-20 18:06 UTC
